### ISSUE TITLE
Error when running Artemis

### ISSUE THREAD

**Issue by JasonLing95** [eastgenomics/eggd_artemis#10]
```
Traceback (most recent call last):
  File "/home/dnanexus/job-GV17BFQ4FxPKgJK30J6KGV69", line 39, in <module>
    exec_code(job_code, _code_filename)
  File "/home/dnanexus/job-GV17BFQ4FxPKgJK30J6KGV69", line 25, in exec_code
    exec(compiled_code, globals())
  File "/home/dnanexus/job-GV17BFQ4FxPKgJK30J6KGV69.code.py", line 792, in <module>
    dxpy.run()
  File "/usr/local/lib/python3.8/dist-packages/dxpy/utils/exec_utils.py", line 150, in run
    result = ENTRY_POINT_TABLE[job['function']](**job['input'])
  File "/home/dnanexus/job-GV17BFQ4FxPKgJK30J6KGV69.code.py", line 665, in main
    multiqc = get_multiqc_report(snv_path.split(',')[0], DX_PROJECT)
  File "/home/dnanexus/job-GV17BFQ4FxPKgJK30J6KGV69.code.py", line 270, in get_multiqc_report
    return multiqc
UnboundLocalError: local variable 'multiqc' referenced before assignment
```

Link to job
https://platform.dnanexus.com/projects/GV0YzGQ4FxPP79K4bGF4zqP4/monitor/job/GV17BFQ4FxPKgJK30J6KGV69

**Comment by Addy81** [comment]
Closing this as it doesn't require any changes to artemis, this was due the little hack on adding single to comply with what dias batch expected the input folder to be called, but this is rectified at batch level.

Link to batch release: https://github.com/eastgenomics/dias_batch_running/releases/tag/v2.0.0
